/*
 * APP_FSM.h
 *
 *  Created on: Feb 27, 2025
 *      Author: 
 */

#ifndef APP_APP_FSM_H_
#define APP_APP_FSM_H_

#define MAX_PE_RETRIES 3  // User-defined max retries for PE

typedef enum {
    STATE_IDLE,
    STATE_START_OWNER_PAIRING,
    STATE_WAITING_FOR_BONDING_DATA,
    STATE_WAITING_FOR_PRIMARY_WAKEUP,
    STATE_PRIMARY_PE,
    STATE_PRIMARY_TDM,
    STATE_WAKEUP_DECISION_MAKING,
    STATE_SECONDARY_PE,
    STATE_VEHICLE_LEVEL_DECISION_MAKING,
    STATE_FUSION_ALGO
} APP_tenuStates;

typedef enum {
    EVENT_OWNER_PAIRING_BUTTON_PRESSED,
    EVENT_SEND_OWNER_PAIRING_COMMAND,
    EVENT_BONDING_DATA_RECEIVED,
    EVENT_PRIMARY_PE_SUCCESSFUL,
    EVENT_PRIMARY_PE_FAILED,
    EVENT_SECONDARY_PE_SUCCESSFUL,
    EVENT_SECONDARY_PE_FAILED,
    EVENT_DEVICE_IN_RANGE,
    EVENT_RECEIVE_DISTANCE,
    EVENT_DISTANCE_BELOW_THRESHOLD,
    EVENT_DISTANCE_ABOVE_THRESHOLD,
    EVENT_FINAL_DISTANCE
} APP_tenuEvents;


// typedef enum {
//     STATE_IDLE,
//     STATE_START_OWNER_PAIRING,
//     STATE_WAITING_FOR_BONDING_DATA,
//     STATE_WAITING_FOR_PRIMARY_WAKEUP,
//     STATE_PRIMARY_PE,
//     STATE_PRIMARY_TDM,
//     STATE_WAKEUP_DECISION_MAKING,
//     STATE_WAITING_FOR_SECONDARY_WAKEUP,
//     STATE_SECONDARY_PE,
//     STATE_SECONDARY_TDM,
//     STATE_VEHICLE_LEVEL_DECISION_MAKING,
//     STATE_FUSION_ALGO
// } APP_tenuStates;

// typedef enum {
//     EVENT_OWNER_PAIRING_BUTTON_PRESSED,
//     EVENT_SEND_OWNER_PAIRING_COMMAND,
//     EVENT_BONDING_DATA_RECEIVED,
//     EVENT_PRIMARY_WAKEUP_RECEIVED,
//     EVENT_SECONDARY_WAKEUP_RECEIVED,
//     EVENT_PRIMARY_PE_SUCCESSFUL,
// 	EVENT_PRIMARY_PE_FAILED,
//     EVENT_SECONDARY_PE_SUCCESSFUL,
//     EVENT_SECONDARY_PE_FAILED,
//     EVENT_SECONDARY_TDM_SUCCESSFUL,
//     EVENT_SECONDARY_TDM_FAILED,
//     EVENT_DEVICE_IN_RANGE,
//     EVENT_RECEIVE_DISTANCE,
//     EVENT_DISTANCE_BELOW_THRESHOLD,
//     EVENT_DISTANCE_ABOVE_THRESHOLD,
//     EVENT_FINAL_DISTANCE
// } APP_tenuEvents;


#define APP_DISTANCE_TRIGGER_THRESHOLD      2
#define APP_MINUMUM_DISTANCE_READINGS       2

void APP_voidFSMHandler(APP_tenuEvents Copy_structEvent);



#endif /* APP_APP_FSM_H_ */
