/*
 * APP_FSM.h
 *
 *  Created on: Feb 27, 2025
 *      Author: 
 */

#ifndef APP_APP_FSM_H_
#define APP_APP_FSM_H_

#define MAX_PE_RETRIES 3  // User-defined max retries for PE
#define MAX_HANDOVER_RETRIES 5

typedef enum {
    STATE_IDLE,
    STATE_TRIGGER_OWNER_PAIRING,
    STATE_WAITING_FOR_VERIFIERS,
    STATE_WAITING_FOR_PK_CERTIFICATE,
    STATE_WAITING_FOR_BONDING_DATA,
    STATE_WAITING_FOR_PRIMARY_WAKEUP,
    STATE_CS_PRIMARY_PE,
    STATE_RSSI_PRIMARY_PE,
    STATE_START_CS_STATE,
    STATE_START_RSSI_STATE,
    STATE_PRIMARY_TDM,
    STATE_WAKEUP_DECISION_MAKING,
    STATE_DISTANCE_MEASUREMENT_INIT,           // Initialize secondary PE process
    STATE_DISTANCE_MEASUREMENT_PROCESSING,     // Processing PE for current anchor
    STATE_DISTANCE_MEASUREMENT_HANDOVER,       // Handling handover between anchors
    STATE_DISTANCE_MEASUREMENT_EVALUATION,     // Evaluate if enough readings collected
    STATE_FUSION_ALGO,
    STATE_VEHICLE_LEVEL_DECISION_MAKING,
    STATE_HANDOVER_CONNECTION_TO_PRIMARY_ANCHOR
} APP_tenuStates;

typedef enum {
    EVENT_OWNER_PAIRING_BUTTON_PRESSED,
    EVENT_SEND_OWNER_PAIRING_COMMAND,
    EVENT_VERIFIERS_RECEIVED,
    EVENT_CERTIFICATE_RECEIVED,
    EVENT_BONDING_DATA_RECEIVED,
    EVENT_PRIMARY_PE_SUCCESSFUL,
    EVENT_DEVICE_DISCONNECTED_FROM_PRIMARY_ANCHOR,
    EVENT_SECONDARY_PE_SUCCESSFUL,
    EVENT_DEVICE_DISCONNECTED_FROM_SECONDARY_ANCHOR,
    EVENT_DEVICE_IN_RANGE,
    EVENT_RECEIVE_DISTANCE,
    EVENT_DISTANCE_BELOW_THRESHOLD,
    EVENT_DISTANCE_ABOVE_THRESHOLD,
    EVENT_FINAL_DISTANCE,
    EVENT_PRIMARY_WAKEUP_RECEIVED,
    EVENT_SECONDARY_WAKEUP_RECEIVED,
    EVENT_HANDOVER_SUCCESS,
    EVENT_HANDOVER_FAILED,
    EVENT_START_FUSION,
    EVENT_TAKE_DECISION
} APP_tenuEvents;

typedef enum{
    APP_NOT_DETERMINED,
    APP_RSSI,
    APP_CS
}APP_tenuRangingType;

typedef enum {
    DIRECTION_FORWARD = 1,
    DIRECTION_BACKWARD = -1
} AnchorTraversalDirection_t;

#define APP_DISTANCE_TRIGGER_THRESHOLD      3
#define APP_MINUMUM_DISTANCE_READINGS       2
#define APP_CS_NO_OF_MEASURING_DISTANCE     1
#define APP_MAX_NO_OF_DEVICES               4

#define TIMEOUT_DISCONNECT                  500
#define TIMEOUT_HANDOVER                    1000

void APP_voidFSMHandler(APP_tenuEvents Copy_enuEvent, uint8_t Copy_u8DeviceId);
#endif /* APP_APP_FSM_H_ */
